# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build Plugin
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: buildPlugin
    - name: Build Plugin Legacy
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: buildPluginLegacy
      #取文件名
    - name: Get Plugin Name
      run: echo "NAME=$(find /home/runner/work/mirai-plugins-pixiv/mirai-plugins-pixiv/build/mirai -name "*.jar" -exec basename {} \;)" >> $GITHUB_ENV
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      if: success()
      with:
        name: ${{ env.NAME }}
        path: /home/runner/work/mirai-plugins-pixiv/mirai-plugins-pixiv/build/mirai/*.jar
        retention-days: 0
        if-no-files-found: error
